// src/app/react/ProductList.tsx
import React, { useEffect, useState } from "react";
import { ProductCard, Product } from "./ProductCard";
import { useNavigate } from "react-router-dom";
import { fetchProducts } from "./ProductService";
import { Link } from "react-router-dom";

export const ProductList: React.FC = () => {
  const [products, setProducts] = useState<Product[]>([]);
  const navigate = useNavigate();

  useEffect(() => {
    const getProducts = async () => {
      const data = await fetchProducts();
      setProducts(data);
    };

    getProducts();
  }, []);

  const handleViewDetails = (product: Product) => {
    navigate(`/products/${product.id}`);
  };

  const navigateAngular = () => {
    window.location.href = "/";
  };

  return (
    <>
      <div className="p-4">
        <h1 className="text-4xl font-bold dark:text-white mt-10 text-center">
          Caseware Assessment - React App
        </h1>
        <div className="flex flex-wrap justify-around mt-10">
          {products.map((product) => (
            <ProductCard
              key={product.id}
              product={product}
              onViewDetails={handleViewDetails}
            />
          ))}
        </div>
      </div>

      <div className="mt-10 flex justify-center">
        <button
          className="bg-slate-500 hover:bg-slate-600 text-white font-bold py-2 px-4 rounded w-full sm:w-auto transition-colors duration-200"
          onClick={navigateAngular}
        >
          Go To Angular App
        </button>
      </div>
    </>
  );
};

// src/app/components/product-list/product-list.component.ts
import { Component, OnInit } from '@angular/core';
import { ProductService } from '../../services/product.service';
import {
  Product,
  ProductCardComponent,
} from '../product-card/product-card.component';
import { Router } from '@angular/router';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-product-list',
  standalone: true,
  templateUrl: './product-list.component.html',
  styleUrl: './product-list.component.css',
  imports: [ProductCardComponent, CommonModule],
})
export class ProductListComponent implements OnInit {
  products: Product[] = [];

  constructor(private productService: ProductService, private router: Router) {}

  ngOnInit(): void {
    this.productService.getProducts().subscribe((data) => {
      this.products = data;
    });
  }

  onProductSelected(product: Product): void {
    this.router.navigate(['/products', product.id]);
  }

  navigateToReact(): void {
    this.router.navigate(['/react']);
  }
}

<h1>Caseware Technical Assessment | Angular App</h1>
<div class="product-list">
  <app-product-card
    *ngFor="let product of products"
    [product]="product"
    (productClicked)="onProductSelected($event)"
  >
  </app-product-card>
</div>

<div class="mt-10 flex justify-center">
  <button
    (click)="navigateToReact()"
    class="bg-slate-500 text-white px-4 py-2 rounded hover:bg-slate-600"
  >
    Go to React
  </button>
</div>
